### ISSUE TITLE
Signet support - bitcoin-core npm package is unmaintained

### ISSUE THREAD

**Issue by openoms** [GaloyMoney/galoy#1387]
After the merge of #1385 the exporter pod is still failing:
```
exporter-5dbcc87b85-852bp                      0/1     CrashLoopBackOff   17 (106s ago)   70m
k3d@debian:~$ k -n galoy-dev-galoy logs exporter-5dbcc87b85-852bp
Defaulted container "exporter" out of: exporter, wait-for-mongodb-migrate (init)
/app/node_modules/bitcoin-core/dist/src/index.js:71
      throw new Error(`Invalid network name "${network}"`, {
      ^

Error: Invalid network name "signet"
    at new Client (/app/node_modules/bitcoin-core/dist/src/index.js:71:13)
    at new BitcoindClient (/app/lib/services/bitcoind/index.js:20:23)
    at Object.<anonymous> (/app/lib/services/bitcoind/index.js:87:33)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
    at require (node:internal/modules/cjs/helpers:102:18)
```

The relevant package: https://github.com/GaloyMoney/galoy/blob/fad58ca3f48f86ad186a31dfbc8b2413c32b88c0/yarn.lock#L3332

https://github.com/ruimarinho/bitcoin-core has it's last commit in Sept 2019 and does not have signet support, neither any RPC methods since Bitcoin Core 0.19 (we are using 22.0 now, 23.0 is the latest).

Is there a more up-to-date alternative to this package?

**Comment by nicolasburtey** [comment]
how many RPC call do we use? maybe we could use the RPC directly instead of the wrapper? @dolcalmi ?

**Comment by nicolasburtey** [comment]
doing our own fork of bitcoin-core would be an alternative
