### ISSUE TITLE
Anchor channels support

### ISSUE THREAD

**Issue by openoms** [GaloyMoney/galoy#1516]
Changing to channels with anchor commitments would improve the security of the node in case of a high fee environment.

Currently the accounting doesn't support the changes in the commitment fees

When removing 
```
protocol.no-anchors=true 
```
from
https://github.com/GaloyMoney/galoy/blob/8d468c4151a0d4b90edbb17370b2f7ea246d1ece/dev/lnd/lnd.conf#L41

The tests fail:

```
  Bitcoind
    ✓ check no wallet (7 ms)
    ✓ create cold wallet (316 ms)
    ✓ create outside wallet (1076 ms)
    ✓ should be funded mining 10 blocks (259 ms)
    ✓ funds outside lnd node (3431 ms)
    ✓ funds lnd1 node (918 ms)

WARN [1659981612148] (140548 on debian): not balanced
    module: "test"
    assetsLiabilitiesDifference: 0
    bookingVersusRealWorldAssets: -330
    assets: -99992363
    liabilities: 99992363
    bankOwnerBalance: 292363
    lnd: 99988893
    lightning: -99989223
    bitcoind: 0
    bitcoin: 0
WARN [1659981613963] (140548 on debian): not balanced
    module: "test"
    assetsLiabilitiesDifference: 0
    bookingVersusRealWorldAssets: -660
    assets: -99984726
    liabilities: 99984726
    bankOwnerBalance: 284726
    lnd: 99977786
    lightning: -99978446
    bitcoind: 0
    bitcoin: 0
WARN [1659981615722] (140548 on debian): not balanced
    module: "test"
    assetsLiabilitiesDifference: 0
    bookingVersusRealWorldAssets: -660
    assets: -99984726
    liabilities: 99984726
    bankOwnerBalance: 284726
    lnd: 99977786
    lightning: -99978446
    bitcoind: 0
    bitcoin: 0
WARN [1659981617569] (140548 on debian): not balanced
    module: "test"
    assetsLiabilitiesDifference: 0
    bookingVersusRealWorldAssets: -990
    assets: -99977089
    liabilities: 99977089
    bankOwnerBalance: 277089
    lnd: 99966679
    lightning: -99967669
    bitcoind: 0
    bitcoin: 0
FAIL test/integration/01-setup/01-lightning-channels.spec.ts (9.735 s)
  Lightning channels
    ✕ opens channel from lnd1 to lnd2 (1699 ms)
    ✕ opens channel from lnd1 to lndOutside1 (1812 ms)
    ✕ opens channel from lndOutside1 to lnd1 (1758 ms)
    ✕ opens channel from lnd1 to lndOutside2 (1846 ms)
    ○ skipped opens private channel from lndOutside1 to lndOutside2
    ○ skipped opensAndCloses channel from lnd1 to lndOutside1

  ● Lightning channels › opens channel from lnd1 to lnd2

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 330

      26 |
      27 |   // TODO: need to go from sats to msats to properly account for every msats spent
    > 28 |   expect(Math.abs(bookingVersusRealWorldAssets)).toBe(0)
         |                                                  ^
      29 | }
      30 |
      31 | const getLedgerAccounts = async () => {

      at checkIsBalanced (test/helpers/check-is-balanced.ts:28:50)
      at Object.<anonymous> (test/integration/01-setup/01-lightning-channels.spec.ts:32:3)

  ● Lightning channels › opens channel from lnd1 to lndOutside1

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 660

      26 |
      27 |   // TODO: need to go from sats to msats to properly account for every msats spent
    > 28 |   expect(Math.abs(bookingVersusRealWorldAssets)).toBe(0)
         |                                                  ^
      29 | }
      30 |
      31 | const getLedgerAccounts = async () => {

      at checkIsBalanced (test/helpers/check-is-balanced.ts:28:50)
      at Object.<anonymous> (test/integration/01-setup/01-lightning-channels.spec.ts:32:3)

  ● Lightning channels › opens channel from lndOutside1 to lnd1

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 660

      26 |
      27 |   // TODO: need to go from sats to msats to properly account for every msats spent
    > 28 |   expect(Math.abs(bookingVersusRealWorldAssets)).toBe(0)
         |                                                  ^
      29 | }
      30 |
      31 | const getLedgerAccounts = async () => {

      at checkIsBalanced (test/helpers/check-is-balanced.ts:28:50)
      at Object.<anonymous> (test/integration/01-setup/01-lightning-channels.spec.ts:32:3)

  ● Lightning channels › opens channel from lnd1 to lndOutside2

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 990

      26 |
      27 |   // TODO: need to go from sats to msats to properly account for every msats spent
    > 28 |   expect(Math.abs(bookingVersusRealWorldAssets)).toBe(0)
         |                                                  ^
      29 | }
      30 |
      31 | const getLedgerAccounts = async () => {

      at checkIsBalanced (test/helpers/check-is-balanced.ts:28:50)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (test/integration/01-setup/01-lightning-channels.spec.ts:32:3)

Summary of all failing tests
FAIL test/integration/01-setup/01-lightning-channels.spec.ts (9.735 s)
  ● Lightning channels › opens channel from lnd1 to lnd2

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 330

      26 |
      27 |   // TODO: need to go from sats to msats to properly account for every msats spent
    > 28 |   expect(Math.abs(bookingVersusRealWorldAssets)).toBe(0)
         |                                                  ^
      29 | }
      30 |
      31 | const getLedgerAccounts = async () => {

      at checkIsBalanced (test/helpers/check-is-balanced.ts:28:50)
      at Object.<anonymous> (test/integration/01-setup/01-lightning-channels.spec.ts:32:3)

  ● Lightning channels › opens channel from lnd1 to lndOutside1

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 660

      26 |
      27 |   // TODO: need to go from sats to msats to properly account for every msats spent
    > 28 |   expect(Math.abs(bookingVersusRealWorldAssets)).toBe(0)
         |                                                  ^
      29 | }
      30 |
      31 | const getLedgerAccounts = async () => {

      at checkIsBalanced (test/helpers/check-is-balanced.ts:28:50)
      at Object.<anonymous> (test/integration/01-setup/01-lightning-channels.spec.ts:32:3)

  ● Lightning channels › opens channel from lndOutside1 to lnd1

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 660

      26 |
      27 |   // TODO: need to go from sats to msats to properly account for every msats spent
    > 28 |   expect(Math.abs(bookingVersusRealWorldAssets)).toBe(0)
         |                                                  ^
      29 | }
      30 |
      31 | const getLedgerAccounts = async () => {

      at checkIsBalanced (test/helpers/check-is-balanced.ts:28:50)
      at Object.<anonymous> (test/integration/01-setup/01-lightning-channels.spec.ts:32:3)

  ● Lightning channels › opens channel from lnd1 to lndOutside2

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 990

      26 |
      27 |   // TODO: need to go from sats to msats to properly account for every msats spent
    > 28 |   expect(Math.abs(bookingVersusRealWorldAssets)).toBe(0)
         |                                                  ^
      29 | }
      30 |
      31 | const getLedgerAccounts = async () => {

      at checkIsBalanced (test/helpers/check-is-balanced.ts:28:50)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (test/integration/01-setup/01-lightning-channels.spec.ts:32:3)


Test Suites: 1 failed, 2 passed, 3 of 25 total
Tests:       4 failed, 2 skipped, 12 passed, 18 total
Snapshots:   0 total
Time:        44.203 s
Ran all test suites.
Done in 47.46s.
```

Related discussion in the past: https://github.com/GaloyMoney/galoy/issues/364

As the `lnd` (physical balance) funds are 330 sats less then the `lightning` funds in accounting.

I figured that would need to add the 330 anchor output to the balance here https://github.com/GaloyMoney/galoy/blob/dee3deafaf2043f106e22ebdecc800b75aa162d5/src/services/lnd/utils.ts#L98, but the used libraries don't really have a good way refer to anchor channels.

Does  anyone have an idea which could lead to the solution here?

**Comment by dolcalmi** [comment]
did you try running `updateEscrows` after channels setup ?

**Comment by nicolasburtey** [comment]
Shouldn't you just updates some magic values in the tests?

We have hard coded how many sats are spent on opening a channel AFAIR. Maybe this value needs to be updated?

**Comment by openoms** [comment]
Tried to lower https://github.com/GaloyMoney/galoy/blob/8803eb77aade8686115026d2b1ee08afc1cc2d77/test/integration/01-setup/01-lightning-channels.spec.ts#L21
but that only adds more errors:
```

  ● Lightning channels › opens channel from lnd1 to lndOutside1

    expect(received).toBe(expected) // Object.is equality

    Expected: -7307
    Received: -7637

      68 |
      69 |     const finalFeeInLedger = await ledgerAdmin.getBankOwnerBalance()
    > 70 |     expect(finalFeeInLedger - initFeeInLedger).toBe(channelFee * -1)
         |                                                ^
      71 |
      72 |     await setChannelFees({ lnd: lnd1, channel, base: 1, rate: 0 })
      73 |     await setChannelFees({ lnd: lndOutside1, channel, base: 1, rate: 0 })

      at Object.<anonymous> (test/integration/01-setup/01-lightning-channels.spec.ts:70:48)
```
