### ISSUE TITLE
some error still have the full stacktrace in production

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy#177]
this one seems to be with an invalid signature:

```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>UnauthorizedError: invalid signature<br> &nbsp; &nbsp;at /usr/src/app/node_modules/express-jwt/lib/index.js:105:22<br> &nbsp; &nbsp;at /usr/src/app/node_modules/jsonwebtoken/verify.js:133:14<br> &nbsp; &nbsp;at getSecret (/usr/src/app/node_modules/jsonwebtoken/verify.js:90:14)<br> &nbsp; &nbsp;at Object.module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:94:10)<br> &nbsp; &nbsp;at verifyToken (/usr/src/app/node_modules/express-jwt/lib/index.js:103:13)<br> &nbsp; &nbsp;at fn (/usr/src/app/node_modules/express-jwt/node_modules/async/lib/async.js:746:34)<br> &nbsp; &nbsp;at /usr/src/app/node_modules/express-jwt/node_modules/async/lib/async.js:1213:16<br> &nbsp; &nbsp;at /usr/src/app/node_modules/express-jwt/node_modules/async/lib/async.js:166:37<br> &nbsp; &nbsp;at /usr/src/app/node_modules/express-jwt/node_modules/async/lib/async.js:706:43<br> &nbsp; &nbsp;at /usr/src/app/node_modules/express-jwt/node_modules/async/lib/async.js:167:37<br> &nbsp; &nbsp;at Immediate.&lt;anonymous&gt; (/usr/src/app/node_modules/express-jwt/node_modules/async/lib/async.js:1206:34)<br> &nbsp; &nbsp;at processImmediate (internal/timers.js:461:21)</pre>
</body>

</html>
```

**Comment by nicolasburtey** [comment]
good question, not sure how I had encountered this issue
