### ISSUE TITLE
remove-phone-code migration crashes

### ISSUE THREAD

**Issue by zoop-btc** [GaloyMoney/galoy#2910]
The migration to [remove-phone-codes](https://github.com/GaloyMoney/galoy/blob/main/src/migrations/2022121620560802-remove-phone-code.ts) deletes a collection. But since it most likely doesn't exist it will crash with the appended error and subsequent migrations aren't run.

```
ERROR: Could not migrate up 2022121620560802-remove-phone-code.ts: ns not found MongoServerError: ns not found
    at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:231:30)
    at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:511:28)
    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:399:12)
    at _write (node:internal/streams/writable:340:10)
    at Writable.write (node:internal/streams/writable:344:10)
    at Socket.ondata (node:internal/streams/readable:774:22)
    at Socket.emit (node:events:511:28)
```

**Comment by nicolasburtey** [comment]
we could probably deleted past migration (the one older than 6 months?) regularly from main. what do you think @bodymindarts ?

**Comment by nicolasburtey** [comment]
@zoop-btc I think has been fixed. can you confirm if you still have the issue?

**Comment by zoop-btc** [comment]
@nicolasburtey can confirm, it's fixed :) thanks
