### ISSUE TITLE
Catch things like bad path references at dev-time-checks in codebase

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy#440]
**An example of this error is captured in PR #437**

### Description [from Slack](https://galoymoney-workspace.slack.com/archives/C025EMR24KB/p1628575226125800?thread_ts=1628545591.117500&cid=C025EMR24KB)

_"A bug has been pushed to testnet, that's why testnet deploy is failing. All our graphql related pods are failing.
This is the error -"_
```
Error: Cannot find module '@domain//errors'
Require stack:
- /app/lib/services/mongoose/invoices.js
- /app/lib/core/lightning/index.js
- /app/lib/core/lightning/wallet.js
- /app/lib/core/wallet-factory.js
- /app/lib/servers/exporter.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
at Function.Module._load (internal/modules/cjs/loader.js:745:27)
at Module.require (internal/modules/cjs/loader.js:961:19)
at require (internal/modules/cjs/helpers.js:92:18)
at Object.<anonymous> (/app/lib/services/mongoose/invoices.js:4:18)
at Module._compile (internal/modules/cjs/loader.js:1072:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
at Module.load (internal/modules/cjs/loader.js:937:32)
at Function.Module._load (internal/modules/cjs/loader.js:778:12)
at Module.require (internal/modules/cjs/loader.js:961:19)
at require (internal/modules/cjs/helpers.js:92:18)
at Object.<anonymous> (/app/lib/core/lightning/index.js:13:20)
at Module._compile (internal/modules/cjs/loader.js:1072:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
at Module.load (internal/modules/cjs/loader.js:937:32)
at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/app/lib/services/mongoose/invoices.js',
'/app/lib/core/lightning/index.js',
'/app/lib/core/lightning/wallet.js',
'/app/lib/core/wallet-factory.js',
'/app/lib/servers/exporter.js'
]
}
```
---

**Comment by vindard** [comment]
For this issue specifically, I found [this related issue](https://github.com/import-js/eslint-plugin-import/issues/915#issuecomment-322898231) that says that the `"import/no-useless-path-segments"` rule can fix this. When I tried it though, **it worked** for absolute imports (e.g. `".//schema"` got linted). **It didn't work** for mapped imports though because the double `//` seems to resolve correctly in the checks but doesn't compile correctly when we build? (cc @samerbuna @dolcalmi)

![Screenshot from 2021-08-10 10-16-05](https://user-images.githubusercontent.com/17693119/128883419-aa52e743-57ae-4adb-9d24-f50301072c04.png)

**Comment by nicolasburtey** [comment]
has this been fixed?

**Comment by vindard** [comment]
> has this been fixed?

Just tested, it seems like our codebase can now correctly resolve things like `import { WalletsRepository } from "@services//mongoose"`

Should we close this?
